resources:
    VideoGamesRecords\CoreBundle\Entity\ChartType:
        properties:
            idType:
                identifier: true
        collectionOperations:
            get: ~
        itemOperations:
            get: ~