resources:
    VideoGamesRecords\CoreBundle\Entity\ChartLib:
        properties:
            idLibChart:
                identifier: true
        collectionOperations:
            get: ~
        itemOperations:
            get: ~