resources:
    VideoGamesRecords\CoreBundle\Entity\Game:
        collectionOperations:
            get:
                normalization_context: {'groups': [game.list]}
                pagination_use_output_walkers: true
            autocomplete:
                method: 'GET'
                normalization_context: { 'groups': [ game.read.mini ] }
                path: '/games/autocomplete'
                swagger_context:
                    parameters:
                        -   name: query
                            in: query
                            required: true
                            type: string
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::autocomplete'
        itemOperations:
            get:
                normalization_context: {'groups': [game.read, game.platforms, platform.read]}
            list-by-letter:
                method: 'GET'
                normalization_context: {'groups': [game.list, game.platforms, platform.read]}
                path: '/games-list-by-letter'
                swagger_context:
                    parameters:
                        - name: letter
                          in: query
                          required: false
                          type: string
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::listByLetter'
                defaults:
                    _api_receive: false
            lost-position:
                method: 'GET'
                normalization_context: {'groups': [game.read.mini]}
                access_control: 'is_granted("ROLE_PLAYER")'
                path: '/games-player-lost-position'
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::listFromPlayerLostPosition'
                defaults:
                    _api_receive: false
            player-ranking-points:
                method: 'GET'
                normalization_context: {'groups': [playerGame.pointChart,playerGame.player,player.read.mini,player.team,team.read.mini,player.country,country.read]}
                path: '/games/{id}/player-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Ranking\PlayerGameController::getRankingPoints'
            player-ranking-medals:
                method: 'GET'
                normalization_context: {'groups': [playerGame.medal,playerGame.player,player.read.mini,player.team,team.read.mini,player.country,country.read]}
                path: '/games/{id}/player-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::playerRankingMedals'
            team-ranking-points:
                method: 'GET'
                normalization_context: {'groups': [teamGame.pointChart, teamGame.team, team.read.mini]}
                path: '/games/{id}/team-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::teamRankingPoints'
            team-ranking-medals:
                method: 'GET'
                normalization_context: {'groups': [teamGame.medal, teamGame.team, team.read.mini]}
                path: '/games/{id}/team-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::teamRankingMedals'
        properties:
            groups:
                subresource:
                    resourceClass: 'VideoGamesRecords\CoreBundle\Entity\Group'
                    collection: true
            topics:
                subresource:
                    resourceClass: 'VideoGamesRecords\CoreBundle\Entity\GameTopic'
                    collection: true
            videos:
                subresource:
                    resourceClass: 'VideoGamesRecords\CoreBundle\Entity\Video'
                    collection: true
