resources:
    VideoGamesRecords\CoreBundle\Entity\Platform:
        attributes:
            pagination_enabled: false
        collectionOperations:
            get:
                normalization_context: {'groups': [platform.read]}
        itemOperations:
            get:
                normalization_context: {'groups': [platform.read]}
            player-ranking-point-chart:
                method: 'GET'
                normalization_context: { 'groups': [ playerPlatform.pointChart,playerPlatform.player,player.read.mini,player.team,team.read.mini,player.country,player.country.read ] }
                path: '/platforms/{id}/player-ranking-point-chart'
                swagger_context:
                    parameters:
                        -   name: id
                            in: path
                            required: true
                            type: integer
                        -   name: maxRank
                            in: query
                            required: false
                            type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlatformController::playerRankingPointChart'