resources:
    VideoGamesRecords\CoreBundle\Entity\PlayerBadge:
        collectionOperations:
            get:
                normalization_context: {'groups': [playerBadge.read, playerBadge.badge, badge.read, badge.game, game.read.mini]}
        itemOperations:
            get: ~