resources:
    VideoGamesRecords\CoreBundle\Entity\Player:
        collectionOperations:
            get:
                normalization_context: {'groups': [player.read.mini, vgr.user.read, user.status.read]}
            stats:
                method: 'GET'
                path: '/players/stats'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::stats'
            player-ranking-point-chart:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.pointChart,player.team,team.read.mini,player.country,country.read]}
                path: '/players/ranking-point-chart'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingPointChart'
            player-ranking-point-game:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.pointGame,player.team,team.read.mini,player.country,country.read]}
                path: '/players/ranking-point-game'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingPointGame'
            player-ranking-point-game-home:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.pointGame,player.team,team.read.mini]}
                path: '/players/ranking-point-game-top-5'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingPointGameTop5'
            player-ranking-medal:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.medal,player.team,team.read.mini,player.country,country.read]}
                path: '/players/ranking-medal'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingMedal'
            player-ranking-cup:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.cup,player.team,team.read.mini,player.country,country.read]}
                path: '/players/ranking-cup'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingCup'
            player-ranking-cup-home:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.cup,player.team,team.read.mini]}
                path: '/players/ranking-cup-top-5'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingCupTop5'
            player-ranking-badge:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini,player.badge,player.team,team.read.mini,player.country,country.read]}
                path: '/players/ranking-badge'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingBadge'
            player-ranking-proof:
                method: 'GET'
                normalization_context: {'groups': [player.read,player.proof,player.team,team.read.mini,player.country,country.read]}
                path: '/players/ranking-proof'
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::rankingProof'
            profile:
                method: 'GET'
                access_control: 'is_granted("IS_AUTHENTICATED_FULLY")'
                normalization_context: {'groups': [user.profile,player.read.mini,team.read.mini]}
                path: '/players/profile'
                controller: 'VideoGamesRecords\CoreBundle\Controller\AuthController::profile'
            profile-team:
                method: 'GET'
                access_control: 'is_granted("IS_AUTHENTICATED_FULLY")'
                normalization_context: {'groups': [team.read.mini, team.leader], 'enable_max_depth':true}
                path: '/players/profile-team'
                controller: 'VideoGamesRecords\CoreBundle\Controller\AuthController::profileTeam'
            profile-player:
                method: 'GET'
                access_control: 'is_granted("IS_AUTHENTICATED_FULLY")'
                normalization_context: {'groups': [player.read.mini]}
                path: '/players/profile-player'
                controller: 'VideoGamesRecords\CoreBundle\Controller\AuthController::profilePlayer'
            autocomplete:
                method: 'GET'
                normalization_context: {'groups': [player.read.mini]}
                path: '/players/autocomplete'
                swagger_context:
                    parameters:
                        - name: query
                          in: query
                          required: true
                          type: string
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlayerController::autocomplete'
        itemOperations:
            get:
                normalization_context: {'groups': [player.read, player.team, team.read.mini, player.user, vgr.user.read, user.status.read, player.country, country.read, player.cup, player.medal, player.proof, player.badge, player.pointGame, player.pointChart]}
            put:
                access_control: 'is_granted("ROLE_PLAYER") and object.getUser() == user'
                denormalization_context: {'groups': [player.put]}
                normalization_context: {'groups': [player.read.mini, player.team, team.read.mini]}