resources:
    VideoGamesRecords\CoreBundle\Entity\TeamBadge:
        collectionOperations:
            get:
                normalization_context: {'groups': [teamBadge.read, teamBadge.badge, badge.read, badge.game, game.read.mini]}
        itemOperations:
            get: ~
            put:
                access_control: 'object.getTeam().getLeader().getUser() == user'
                denormalization_context: { 'groups': [ teamBadge.put ] }
                normalization_context: { 'groups': [ teamBadge.read, teamBadge.badge, badge.read, badge.game, game.read.mini ] }