services:
    VideoGamesRecords\CoreBundle\Command\GameOfDayAddCommand:
        class: VideoGamesRecords\CoreBundle\Command\GameOfDayAddCommand
        arguments:
            - '@vgr.core.manager.game_day'
        tags:
            - { name: 'console.command', command: 'vgr-core:game-of-day-add' }
