services:

  _defaults:
    autowire: false
    autoconfigure: true
    public: true

  # OK
  VideoGamesRecords\CoreBundle\Controller\Picture\Show:
    arguments:
      - '@aws.s3'
    calls:
      - [ setContainer, [ "@service_container" ] ]


  # TODO
  VideoGamesRecords\CoreBundle\Controller\ScorePlatformController:
    arguments:
      - '@vgr.core.manager.score_manager'
      - '@vgr.core.security.user_provider'
    calls:
      - [ setContainer, [ "@service_container" ] ]
