services:

    _defaults:
        autowire: false
        autoconfigure: true
        public: true

    VideoGamesRecords\CoreBundle\Controller\ScorePlatformController:
        arguments:
            - '@vgr.core.manager.score_manager'
            - '@vgr.core.security.user_provider'
        calls:
            - [ setContainer, [ "@service_container" ] ]