services:
    vgr.core.data_provider.can_ask_proof:
        class: VideoGamesRecords\CoreBundle\DataProvider\CanAskProofProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    vgr.core.data_provider.proof_in_progress:
        class: VideoGamesRecords\CoreBundle\DataProvider\ProofInProgressProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    vgr.core.data_provider.top_score:
        class: VideoGamesRecords\CoreBundle\DataProvider\TopScoreProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    #ranking/player
    vgr.core.data_provider.ranking.player:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.player_platform:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerPlatformRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.player_country:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerCountryRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.player_game:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerGameRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.player_group:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerGroupRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.player_chart:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerChartRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.player_serie:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Player\PlayerSerieRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    #ranking/team
    vgr.core.data_provider.ranking.team:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Team\TeamRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.team_game:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Team\TeamGameRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.team_group:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Team\TeamGroupRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'

    vgr.core.data_provider.ranking.team_chart:
        class: VideoGamesRecords\CoreBundle\DataProvider\Ranking\Team\TeamChartRankingQuery
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.security.user_provider'


