services:

  VideoGamesRecords\CoreBundle\Doctrine\DistinctExtension:
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: -8 }

  VideoGamesRecords\CoreBundle\Doctrine\TranslationExtension:
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection, priority: -8 }
      - { name: api_platform.doctrine.orm.query_extension.item, priority: -8 }
