services:
    VideoGamesRecords\CoreBundle\EventSubscriber\PlayerChartValueSubscriber:
        class:  VideoGamesRecords\CoreBundle\EventSubscriber\PlayerChartValueSubscriber
        tags: [ { name: 'kernel.event_subscriber'} ]
    VideoGamesRecords\CoreBundle\EventSubscriber\PlayerBadgeSetTitleSubscriber:
        arguments:
            - '@translator'
            - '@vgr.core.manager.badge'
        class: VideoGamesRecords\CoreBundle\EventSubscriber\PlayerBadgeSetTitleSubscriber
        tags: [ { name: 'kernel.event_subscriber' } ]






