services:
    vgr.core.handler.badge.player:
        class: VideoGamesRecords\CoreBundle\Handler\Badge\PlayerBadgeHandler
        arguments:
            - '@doctrine.orm.entity_manager'

    vgr.core.handler.badge.player_country:
        class: VideoGamesRecords\CoreBundle\Handler\Badge\PlayerCountryBadgeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.ranking.provider.player.player_country'

    vgr.core.handler.badge.player_game:
        class: VideoGamesRecords\CoreBundle\Handler\Badge\PlayerMasterBadgeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.ranking.provider.player.player_game'

    vgr.core.handler.badge.player_platform:
        class: VideoGamesRecords\CoreBundle\Handler\Badge\PlayerPlatformBadgeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.ranking.provider.player.player_platform'

    vgr.core.handler.badge.team_game:
        class: VideoGamesRecords\CoreBundle\Handler\Badge\TeamMasterBadgeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@vgr.core.ranking.provider.team.team_game'

    vgr.core.handler.score_investigation:
        class: VideoGamesRecords\CoreBundle\Handler\ScoreInvestigationHandler
        arguments:
            - '@doctrine.orm.entity_manager'
