services:
    vgr.core.manager.game:
        class: VideoGamesRecords\CoreBundle\Manager\GameManager
        arguments:
            - '@vgr.core.repository.game'

    vgr.core.manager.game_day:
        class: VideoGamesRecords\CoreBundle\Manager\GameOfDayManager
        arguments:
            - '@vgr.core.repository.game'
            - '@vgr.core.repository.game_day'

    vgr.core.manager.lost_position:
        class: VideoGamesRecords\CoreBundle\Manager\LostPositionManager
        arguments:
            - '@vgr.core.repository.lost_position'

    vgr.core.manager.score_manager:
        class: VideoGamesRecords\CoreBundle\Manager\ScoreManager
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'

    vgr.core.manager.badge:
        class: VideoGamesRecords\CoreBundle\Manager\BadgeManager
        calls:
            - ['addStrategy', ['@vgr.core.manager.strategy.badge.default']]
            - ['addStrategy', [ '@vgr.core.manager.strategy.badge.value_prefix']]
            - ['addStrategy', [ '@vgr.core.manager.strategy.badge.value_suffix']]
            - ['addStrategy', ['@vgr.core.manager.strategy.badge.game']]
            - ['addStrategy', ['@vgr.core.manager.strategy.badge.serie']]
            - ['addStrategy', ['@vgr.core.manager.strategy.badge.platform']]
            - ['addStrategy', ['@vgr.core.manager.strategy.badge.country']]

    vgr.core.manager.strategy.badge.default:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\DefaultType
        arguments:
            - '@translator'

    vgr.core.manager.strategy.badge.game:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\GameType
        arguments:
            - '@translator'

    vgr.core.manager.strategy.badge.serie:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\SerieType
        arguments:
            - '@translator'

    vgr.core.manager.strategy.badge.platform:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\PlatformType
        arguments:
            - '@translator'

    vgr.core.manager.strategy.badge.country:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\CountryType
        arguments:
            - '@translator'

    vgr.core.manager.strategy.badge.value_prefix:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\ValuePrefixType
        arguments:
            - '@translator'

    vgr.core.manager.strategy.badge.value_suffix:
        class: VideoGamesRecords\CoreBundle\Manager\Strategy\Badge\ValueSuffixType
        arguments:
            - '@translator'

