services:
    vgr.core.repository.game:
        class: VideoGamesRecords\CoreBundle\Repository\Game
        arguments:
            - '@doctrine'

    vgr.core.repository.game_day:
        class: VideoGamesRecords\CoreBundle\Repository\GameDay
        arguments:
            - '@doctrine'
