services:
    vgr.core.repository.badge:
        class: VideoGamesRecords\CoreBundle\Repository\BadgeRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Badge

    vgr.core.repository.chart_lib:
        class: VideoGamesRecords\CoreBundle\Repository\ChartLibRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\ChartLib

    vgr.core.repository.chart:
        class: VideoGamesRecords\CoreBundle\Repository\ChartRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Chart

    vgr.core.repository.chart_type:
        class: VideoGamesRecords\CoreBundle\Repository\ChartTypeRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\ChartType

    vgr.core.repository.game_day:
        class: VideoGamesRecords\CoreBundle\Repository\GameDayRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\GameDay

    vgr.core.repository.game:
        class: VideoGamesRecords\CoreBundle\Repository\GameRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Game

    vgr.core.repository.group:
        class: VideoGamesRecords\CoreBundle\Repository\GroupRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Group

    vgr.core.repository.lost_position:
        class: VideoGamesRecords\CoreBundle\Repository\LostPositionRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\LostPosition

    vgr.core.repository.picture:
        class: VideoGamesRecords\CoreBundle\Repository\PictureRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Picture

    vgr.core.repository.platform:
        class: VideoGamesRecords\CoreBundle\Repository\PlatformRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Platform

    vgr.core.repository.player_badge:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerBadgdeRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerBadge

    vgr.core.repository.player_chart_lib:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerChartLibRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerChartLib

    vgr.core.repository.player_chart:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerChartRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerChart

    vgr.core.repository.player_chart_status:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerChartStatusRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerChartStatus

    vgr.core.repository.player_game:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerGameRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerGame

    vgr.core.repository.player_group:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerGroupRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerGroup

    vgr.core.repository.player_platform:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerPlatformRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerPlatform

    vgr.core.repository.player:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Player

    vgr.core.repository.player_serie:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerSerieRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerSerie

    vgr.core.repository.player_status:
        class: VideoGamesRecords\CoreBundle\Repository\PlayerStatusRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\PlayerStatus

    vgr.core.repository.proof:
        class: VideoGamesRecords\CoreBundle\Repository\ProofRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Proof

    vgr.core.repository.proof_request:
        class: VideoGamesRecords\CoreBundle\Repository\ProofRequestRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\ProofRequest

    vgr.core.repository.rule:
        class: VideoGamesRecords\CoreBundle\Repository\RuleRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Rule

    vgr.core.repository.serie:
        class: VideoGamesRecords\CoreBundle\Repository\SerieRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Serie

    vgr.core.repository.team_badge:
        class: VideoGamesRecords\CoreBundle\Repository\TeamBadgeRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\TeamBadge

    vgr.core.repository.team_chart:
        class: VideoGamesRecords\CoreBundle\Repository\TeamChartRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\TeamChart

    vgr.core.repository.team_game:
        class: VideoGamesRecords\CoreBundle\Repository\TeamGameRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\TeamGame

    vgr.core.repository.team_group:
        class: VideoGamesRecords\CoreBundle\Repository\TeamGroupRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\TeamGroup

    vgr.core.repository.team:
        class: VideoGamesRecords\CoreBundle\Repository\TeamRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Team

    vgr.core.repository.team_request:
        class: VideoGamesRecords\CoreBundle\Repository\TeamRequestRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\TeamRequest

    vgr.core.repository.video_comment:
        class: VideoGamesRecords\CoreBundle\Repository\VideoCommentRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\VideoComment

    vgr.core.repository.video:
        class: VideoGamesRecords\CoreBundle\Repository\VideoRepository
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
            - VideoGamesRecords\CoreBundle\Entity\Video







































