services:
    sonata.admin.serie:
        class: VideoGamesRecords\CoreBundle\Admin\SerieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "Serie" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Serie
            - ~
    sonata.admin.game:
        class: VideoGamesRecords\CoreBundle\Admin\GameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "Game" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Game
            - ~
        calls:
            - [ setTemplate, [show, VideoGamesRecordsCoreBundle:Admin:game_show.html.twig]]
    sonata.admin.group:
        class: VideoGamesRecords\CoreBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "Group" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Group
            - ~
    sonata.admin.chart:
        class: VideoGamesRecords\CoreBundle\Admin\ChartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "Chart" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Chart
            - ~
    sonata.admin.chartType:
        class: VideoGamesRecords\CoreBundle\Admin\ChartTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "ChartType" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\ChartType
            - ~
    sonata.admin.chartLib:
        class: VideoGamesRecords\CoreBundle\Admin\ChartLibAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "ChartLib", show_in_dashboard: false }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\ChartLib
            - ~
    sonata.admin.platform:
        class: VideoGamesRecords\CoreBundle\Admin\PlatformAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "VgrCoreBundle", label: "Platform" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Platform
            - ~
