services:
    sonata.admin.vgr.core.serie:
        class: VideoGamesRecords\CoreBundle\Admin\SerieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.serie" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Serie
            - ~
    sonata.admin.vgr.core.game:
        class: VideoGamesRecords\CoreBundle\Admin\GameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.game" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Game
            - ~
        calls:
            - [ setTemplate, ['show', 'VideoGamesRecordsCoreBundle:Admin:game_show.html.twig']]
    sonata.admin.vgr.core.group:
        class: VideoGamesRecords\CoreBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.group" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Group
            - ~
    sonata.admin.vgr.core.chart:
        class: VideoGamesRecords\CoreBundle\Admin\ChartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.chart" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Chart
            - ~
    sonata.admin.vgr.core.chart_type:
        class: VideoGamesRecords\CoreBundle\Admin\ChartTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.chart.type" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\ChartType
            - ~
    sonata.admin.vgr.core.chart_lib:
        class: VideoGamesRecords\CoreBundle\Admin\ChartLibAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.chart.lib", show_in_dashboard: false }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\ChartLib
            - ~
    sonata.admin.vgr.core.platform:
        class: VideoGamesRecords\CoreBundle\Admin\PlatformAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games", label: "label.platform" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Platform
            - ~
    sonata.admin.vgr.core.player:
        class: VideoGamesRecords\CoreBundle\Admin\PlayerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.players", label: "label.player" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Player
            - ~
    sonata.admin.vgr.core.game_topic:
        class: VideoGamesRecords\CoreBundle\Admin\GameTopicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games.messages", label: "label.topic" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\GameTopic
            - ~
    sonata.admin.vgr.core.game_message:
        class: VideoGamesRecords\CoreBundle\Admin\GameMessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.games.messages", label: "label.message" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\GameMessage
            - ~
    sonata.admin.vgr.core.playerchart:
        class: VideoGamesRecords\CoreBundle\Admin\PlayerChartAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.scores", label: "label.playerChart" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\PlayerChart
            - ~
    sonata.admin.vgr.core.playerchart_lib:
        class: VideoGamesRecords\CoreBundle\Admin\PlayerChartLibAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.scores", label: "label.playerChartLib", show_in_dashboard: false }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\PlayerChartLib
            - ~
    sonata.admin.team:
        class: VideoGamesRecords\CoreBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.players", label: "label.team" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Team
            - ~
    sonata.admin.proof.request:
        class: VideoGamesRecords\CoreBundle\Admin\ProofRequestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.proofs", label: "label.request" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\ProofRequest
            - ~
    sonata.admin.proof.proof:
        class: VideoGamesRecords\CoreBundle\Admin\ProofAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.proofs", label: "label.proof" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Proof
            - ~
        calls:
            - [ setTemplate, ['show', 'VideoGamesRecordsCoreBundle:Admin:proof_show.html.twig']]
    osnata.admin.proof.picture:
        class: VideoGamesRecords\CoreBundle\Admin\PictureAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.proofs", label: "label.picture" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Picture
            - ~
        calls:
            - [ setTemplate, ['show', 'VideoGamesRecordsCoreBundle:Admin:picture_show.html.twig']]
    sonata.admin.proof.video:
        class: VideoGamesRecords\CoreBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.proofs", label: "label.video" }
        arguments:
            - ~
            - VideoGamesRecords\CoreBundle\Entity\Video
            - ~
        calls:
            - [ setTemplate, ['show', 'VideoGamesRecordsCoreBundle:Admin:video_show.html.twig']]

