resources:
    VideoGamesRecords\CoreBundle\Entity\GameTopic:
        subresourceOperations:
            api_games_topics_get_subresource:
                method: 'GET'
                normalization_context: {'groups': [game.topic.list, player.read.mini]}
        collectionOperations:
            post:
                access_control: 'is_granted("ROLE_PLAYER")'
                denormalization_context: {'groups': [game.topic.post]}
                normalization_context: {'groups': [game.topic.read]}
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\GameMessage:
        collectionOperations:
            get:
                method: 'GET'
                normalization_context: {'groups': [game.message.list, player.read.mini, game.topic.read, game.read.mini]}
            post: ~
        itemOperations:
            get: ~
            put:
                access_control: 'is_granted("ROLE_PLAYER")'
                denormalization_context: {'groups': [game.message.put]}
                normalization_context: {'groups': [game.message.read]}
