resources:
    VideoGamesRecords\CoreBundle\Entity\Serie:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\Game:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
            list-by-letter:
                method: 'GET'
                path: '/game/list-by-letter'
                swagger_context:
                    parameters:
                        - name: letter
                          in: query
                          required: false
                          type: string
                        - name: locale
                          in: query
                          required: false
                          type: string
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::listByLetter'
                defaults:
                    _api_receive: false
            player-ranking-points:
                method: 'GET'
                path: '/game/{id}/player-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::playerRankingPoints'
            player-ranking-medals:
                method: 'GET'
                path: '/game/{id}/player-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::playerRankingMedals'
            team-ranking-points:
                method: 'GET'
                path: '/game/{id}/team-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::teamRankingPoints'
            team-ranking-medals:
                method: 'GET'
                path: '/game/{id}/team-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GameController::teamRankingMedals'
        properties:
            groups:
                subresource:
                    resourceClass: 'VideoGamesRecords\CoreBundle\Entity\Group'
                    collection: true
    VideoGamesRecords\CoreBundle\Entity\Group:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
            player-ranking-points:
                method: 'GET'
                path: '/group/{id}/player-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GroupController::playerRankingPoints'
            player-ranking-medals:
                method: 'GET'
                path: '/group/{id}/player-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GroupController::playerRankingMedals'
            team-ranking-points:
                method: 'GET'
                path: '/group/{id}/team-ranking-points'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GroupController::teamRankingPoints'
            team-ranking-medals:
                method: 'GET'
                path: '/group/{id}/team-ranking-medals'
                swagger_context:
                    parameters:
                        - name: id
                          in: path
                          required: true
                          type: integer
                        - name: maxRank
                          in: query
                          required: false
                          type: integer
                        - name: idPlayer
                          in: query
                          required: false
                          type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\GroupController::teamRankingMedals'
        properties:
            charts:
                subresource:
                    resourceClass: 'VideoGamesRecords\CoreBundle\Entity\Chart'
                    collection: true
    VideoGamesRecords\CoreBundle\Entity\Chart:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\PlayerGame:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\PlayerGroup:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\PlayerChart:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\Player:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~
    VideoGamesRecords\CoreBundle\Entity\Platform:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~