services:
#    vgr_default.example:
#        class: Vgr\DefaultBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    vgr.twig_extension:
        class: VideoGamesRecords\CoreBundle\Twig\VgrExtension
        public: false
        tags:
            - { name: twig.extension }
    entity.event_listener.playerchart_update:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\PlayerChartUpdateListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate}
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate}
    vgr.event_listener.login_listener:
        class: VideoGamesRecords\CoreBundle\EventListener\LoginListener
        arguments: ["@=service('doctrine').getRepository('VideoGamesRecordsCoreBundle:User')"]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
