services:
    VideoGamesRecords\CoreBundle\Command\ChartCommand:
        class: VideoGamesRecords\CoreBundle\Command\ChartCommand
        arguments: [null, '@doctrine.orm.entity_manager']
        public: true
        tags:
            - { name: 'console.command' }

    VideoGamesRecords\CoreBundle\Twig\VgrExtension:
        public: false
        tags:
            - { name: twig.extension }
    entity.event_listener.playerchart_update:
        class: VideoGamesRecords\CoreBundle\EventListener\Entity\PlayerChartUpdateListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate}
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate}
    vgr.event_listener.login_listener:
        class: VideoGamesRecords\CoreBundle\EventListener\LoginListener
        arguments: ["@=service('doctrine').getRepository('VideoGamesRecordsCoreBundle:Player')"]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    VideoGamesRecords\CoreBundle\Controller\Api\GameController:
        arguments: ['@serializer']
        public: true
    VideoGamesRecords\CoreBundle\Controller\Api\RankingController:
        arguments: ['@serializer']
        public: true
    array_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
        public: false
        tags: [serializer.normalizer]
    json_encoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        public: false
        tags: [serializer.encoder]
    vgr.game:
        class:    VideoGamesRecords\CoreBundle\Service\Game
        arguments: [
            "@=service('doctrine.orm.default_entity_manager')",
            "%kernel.root_dir%"
            ]
