services:
#    vgr_default.example:
#        class: Vgr\DefaultBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    vgr.twig_extension:
        class: VideoGamesRecords\CoreBundle\Twig\VgrExtension
        public: false
        tags:
            - { name: twig.extension }
