services:
#    vgr_default.example:
#        class: Vgr\DefaultBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    vgr.twig_extension:
        class: VideoGamesRecords\CoreBundle\Twig\VgrExtension
        public: false
        tags:
            - { name: twig.extension }
    entity.event_listener.userchart_update:
        class:  VideoGamesRecords\CoreBundle\EventListener\Entity\UserChartUpdateListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate}
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate}
