VideoGamesRecords\CoreBundle\Entity\ChartType:
  attributes:
    idType:
      groups:
        - 'chart_show'
        - 'playerChart_show'
    name:
    mask:
      groups:
        - 'chart_show'
        - 'playerChart_show'
    parseMask:
      groups:
        - 'chart_show'
        - 'playerChart_show'
