VideoGamesRecords\CoreBundle\Entity\ChartLib:
  attributes:
    idLibChart:
      groups:
        - 'chart_show'
    name:
      groups:
        - 'chart_show'
    type:
      groups:
        - 'chart_show'
