ProjetNormandie\CountryBundle\Entity\Country:
  attributes:
    id:
      groups:
        - 'player.country.read'
    name:
      groups:
        - 'player.country.read'
    codeIso2:
      groups:
        - 'player.country.read'

