VideoGamesRecords\CoreBundle\Entity\Game:
  attributes:
    id:
      groups:
        - 'game.show'
        - 'game.list'
        - 'group.show'
        - 'chart.show'
        - 'chart.label.read'
    picture:
      groups:
        - 'game.show'
        - 'game.list'
    status:
      groups: []
    etat:
      groups: []
    dateActivation:
      groups: []
    boolDlc:
      groups: []
    nbChart:
      groups:
        - 'game.show'
        - 'game.list'
    nbPost:
      groups:
        - 'game.show'
        - 'game.list'
    nbPlayer:
      groups:
        - 'game.show'
        - 'game.list'
    nbTeam:
      groups:
        - 'game.show'
        - 'game.list'
    ordre:
      groups: []
    serie:
      groups:
        - 'game.show'
    badge:
      groups:
        - 'game.show'
    platforms:
      groups:
        - 'platform.show'
    name:
      groups:
        - 'game.show'
        - 'game.list'
        - 'group.show'
        - 'chart.show'
        - 'chart.label.read'
    rules:
      groups:
        - 'game.show'
        - 'group.show'
        - 'chart.show'
    slug:
        - 'game.show'
        - 'game.list'
    createdAt:
      groups:
        - 'game.show'
    updatedAt:
        - 'game.show'
