VideoGamesRecords\CoreBundle\Entity\Game:
  attributes:
    id:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.read.mini'
    picture:
      groups:
        - 'game.read'
    groups:
      groups:
        - 'game.groups'
    status:
      groups: []
    etat:
      groups: []
    publishedAt:
      groups: []
    boolDlc:
      groups: []
    boolRanking:
      groups:
        - 'game.list'
        - 'game.read'
    nbChart:
      groups:
        - 'game.list'
        - 'game.read'
    nbPost:
      groups:
        - 'game.list'
        - 'game.read'
    nbPlayer:
      groups:
        - 'game.list'
        - 'game.read'
    nbTeam:
      groups:
        - 'game.read'
    ordre:
      groups: []
    serie:
      groups:
        - 'game.read'
    badge:
      groups: []
    platforms:
      groups:
        - 'platform.read'
    name:
      groups:
        - 'game.list'
        - 'game.read'
        - 'game.read.mini'
    rules:
      groups:
        - 'game.read'
    slug:
      groups:
        - 'game.list'
        - 'game.read'
    createdAt:
      groups: []
    updatedAt:
      groups: []
