VideoGamesRecords\CoreBundle\Entity\Game:
  attributes:
    id:
      groups:
        - 'game.list'
        - 'game.list.letter'
        - 'game.show'
        - 'game.show.mini'
        - 'chart.label.read'
    picture:
      groups:
        - 'game.show'
    status:
      groups: []
    etat:
      groups: []
    publishedAt:
      groups: []
    boolDlc:
      groups: []
    boolRanking:
      groups:
        - 'game.list'
        - 'game.show'
    nbChart:
      groups:
        - 'game.list'
        - 'game.list.letter'
        - 'game.show'
    nbPost:
      groups:
        - 'game.list'
        - 'game.list.letter'
        - 'game.show'
    nbPlayer:
      groups:
        - 'game.list'
        - 'game.list.letter'
        - 'game.show'
    nbTeam:
      groups:
        - 'game.show'
    ordre:
      groups: []
    serie:
      groups:
        - 'game.show'
    badge:
      groups: []
    platforms:
      groups:
        - 'platform.show'
    name:
      groups:
        - 'game.list'
        - 'game.list.letter'
        - 'game.show'
        - 'game.show.mini'
        - 'chart.label.read'
    rules:
      groups:
        - 'game.show'
    slug:
        - 'game.list'
        - 'game.list.letter'
        - 'game.show'
    createdAt:
      groups:
        - 'game.show'
    updatedAt:
        - 'game.show'
