VideoGamesRecords\CoreBundle\Entity\Game:
  attributes:
    id:
      groups:
        - 'game_show'
        - 'game_list'
        - 'group_show'
        - 'chart_show'
    picture:
      groups:
        - 'game_show'
        - 'game_list'
    status:
      groups: []
    etat:
      groups: []
    dateActivation:
      groups: []
    boolDlc:
      groups: []
    nbChart:
      groups:
        - 'game_show'
        - 'game_list'
    nbPost:
      groups:
        - 'game_show'
        - 'game_list'
    nbPlayer:
      groups:
        - 'game_show'
        - 'game_list'
    nbTeam:
      groups:
        - 'game_show'
        - 'game_list'
    ordre:
      groups: []
    serie:
      groups:
        - 'game_show'
    badge:
      groups:
        - 'game_show'
    platforms:
      groups:
        - 'platform_show'
    name:
      groups:
        - 'game_show'
        - 'game_list'
        - 'group_show'
        - 'chart_show'
    slug:
        - 'game_show'
        - 'game_list'
    createdAt:
      groups:
        - 'game_show'
    updatedAt:
        - 'game_show'
