VideoGamesRecords\CoreBundle\Entity\GameTopic:
  attributes:
    id:
      groups:
        - 'game.topic.list'
        - 'game.topic.read'
    libTopic:
      groups:
        - 'game.topic.list'
        - 'game.topic.read'
        - 'game.topic.post'
    game:
      groups:
        - 'game.show.mini'
        - 'game.topic.post'
    player:
      groups:
        - 'game.topic.list'
        - 'game.topic.post'
    messages:
      groups:
        - 'game.topic.post'
    createdAt:
      groups:
        - 'game.topic.list'