VideoGamesRecords\CoreBundle\Entity\Group:
  attributes:
    id:
      groups:
        - 'group.list'
        - 'game.groups'
        - 'group.show'
        - 'chart.show'
        - 'chart.label.read'
    game:
      groups:
        - 'group.show'
        - 'chart.show'
        - 'chart.label.read'
    boolDlc:
      groups:
        - 'game.groups'
    nbChart:
      groups:
        - 'group.list'
        - 'game.groups'
        - 'group.show'
    nbPost:
      groups:
        - 'group.list'
        - 'game.groups'
        - 'group.show'
    nbPlayer:
      groups:
        - 'group.list'
        - 'game.groups'
        - 'group.show'
    name:
      groups:
        - 'group.list'
        - 'game.groups'
        - 'group.show'
        - 'chart.show'
        - 'chart.label.read'
    slug:
      groups:
        - 'group.list'
        - 'game.groups'
        - 'group.show'
    createdAt:
      groups:
        - 'group.show'
    updatedAt:
      groups:
        - 'group.show'
