VideoGamesRecords\CoreBundle\Entity\Platform:
  attributes:
    id:
      groups:
        - 'platform.show'
    libPlatform:
      groups:
        - 'platform.show'
    picture:
      groups:
        - 'game.show'
        - 'game.list'
    status:
      groups: []
    class:
      groups: []
