VideoGamesRecords\CoreBundle\Entity\Platform:
  attributes:
    idPlatform:
      groups:
        - 'platform_show'
    libPlatform:
      groups:
        - 'platform_show'
    picture:
      groups:
        - 'game_show'
        - 'game_list'
    status:
      groups: []
    class:
      groups: []
