VideoGamesRecords\CoreBundle\Entity\PlayerChartStatus:
  attributes:
    id:
      groups:
        - 'playerChartStatus.read'
    label:
      groups:
        - 'playerChartStatus.read'
    boolRanking:
    boolSendProof:
