VideoGamesRecords\CoreBundle\Entity\Player:
  attributes:
    id:
      groups:
        - 'player.show'
        - 'user.profile'
        - 'player.put'
    pseudo:
      groups:
        - 'player.show'
    rankPointChart:
      groups:
        - 'player.pointChart'
    pointChart:
      groups:
        - 'player.pointChart'
    rankPointGame:
      groups:
        - 'player.pointGame'
    pointGame:
      groups:
        - 'player.pointGame'
    rankMedal:
      groups:
        - 'player.medal'
    chartRank0:
      groups:
        - 'player.medal'
    chartRank1:
      groups:
        - 'player.medal'
    chartRank2:
      groups:
        - 'player.medal'
    chartRank3:
      groups:
        - 'player.medal'
    rankCup:
      groups:
        - 'player.cup'
    gameRank0:
      groups:
        - 'player.cup'
    gameRank1:
      groups:
        - 'player.cup'
    gameRank2:
      groups:
        - 'player.cup'
    gameRank3:
      groups:
        - 'player.cup'
    avatar:
      groups:
        - 'ranking_point'
        - 'ranking_medal'
        - 'player.profile'
        - 'team.leader.show'
    team:
      groups:
        - 'user.profile'
        - 'team.show'
        - 'player.put'
    country:
      groups: []