VideoGamesRecords\CoreBundle\Entity\PlayerChart:
  attributes:
    idPlayerChart:
      groups:
        - 'playerChart_show'
        - 'playerChart.read'
        - 'playerChart.write'
    chart:
      groups:
        - 'playerChart.read'
        - 'playerChart.write'
    player:
      groups:
        - 'playerChart.read'
        - 'playerChart.write'
        - 'player_show'
    rank:
      groups:
        - 'ranking'
    nbEqual:
      groups:
        - 'ranking'
    pointChart:
      groups:
        - 'ranking'
    status:
      groups:
        - 'ranking'
        - 'playerChart_show'
    proof:
      groups:
        - 'ranking'
    isTopScore:
    dateInvestigation:
      groups:
        - 'ranking'
    platform:
      groups:
        - 'ranking'
        - 'playerChart.read'
        - 'playerChart_show'
        - 'playerChart.write'
    dateModif:
      groups:
        - 'ranking'
    createdAt:
      groups:
        - 'ranking'
    updatedAt:
      groups:
        - 'ranking'
    libs:
      groups:
        - 'playerChart.read'
        - 'playerChart_show'
        - 'playerChart.write'

