VideoGamesRecords\CoreBundle\Entity\PlayerChart:
  attributes:
    id:
      groups:
        - 'playerChart.read'
        - 'playerChart.write'
        - 'playerChart.ranking'
    chart:
      groups:
        - 'playerChart.read'
        - 'playerChart.write'
    player:
      groups:
        - 'playerChart.read'
        - 'playerChart.write'
        - 'playerChart.player'
    rank:
      groups:
        - 'playerChart.read'
        - 'playerChart.ranking'
        - 'chart.top-score'
    nbEqual:
      groups:
        - 'playerChart.ranking'
    pointChart:
      groups:
        - 'playerChart.ranking'
    status:
      groups:
        - 'playerChart.status'
    proof:
      groups:
        - 'playerChart.ranking'
        - 'playerChart.proof'
    isTopScore:
    dateInvestigation:
      groups:
        - 'playerChart.ranking'
    platform:
      groups:
        - 'playerChart.ranking'
        - 'playerChart.write'
        - 'playerChart.platform'
    lastUpdate:
      groups:
        - 'playerChart.ranking'
    createdAt:
      groups: []
    updatedAt:
      groups: []
    libs:
      groups:
        - 'playerChart.read'
        - 'playerChart.write'
        - 'playerchart.libs'

