VideoGamesRecords\CoreBundle\Entity\PlayerChartStatus:
  attributes:
    id:
      groups:
        - 'playerChartStatus.show'
    label:
      groups:
        - 'playerChartStatus.show'
    boolRanking:
    boolSendProof:
