VideoGamesRecords\CoreBundle\Entity\PlayerGame:
  attributes:
    player:
      groups:
        - 'playerGame.player'
    game:
      groups:
        - 'playerGame.game'
    rankPointChart:
      groups:
        - 'playerGame.pointChart'
    rankMedal:
      groups:
        - 'playerGame.medal'
    chartRank0:
      groups:
        - 'playerGame.medal'
    chartRank1:
      groups:
        - 'playerGame.medal'
    chartRank2:
      groups:
        - 'playerGame.medal'
    chartRank3:
      groups:
        - 'playerGame.medal'
    chartRank4:
    chartRank5:
    pointChart:
      groups:
        - 'playerGame.pointChart'
    pointChartWithoutDlc:
      groups:
        - 'playerGame.pointChart'
    nbChart:
      groups:
        - 'playerGame.pointChart'
        - 'playerGame.medal'
    nbChartProven:
      groups:
        - 'playerGame.pointChart'
        - 'playerGame.medal'
    nbChartWithoutDlc:
    nbChartProvenWithoutDlc:
    pointGame:
      groups:
        - 'playerGame.pointChart'
    nbEqual:
      groups:
        - 'playerGame.pointChart'
