VideoGamesRecords\CoreBundle\Entity\PlayerBadge:
  attributes:
    badge:
      groups:
        - 'playerBadge.badge'
    player:
      groups:
        - 'playerBadge.player'
    createdAt:
      groups:
        - 'playerBadge.read'
    endedAt:
      groups:
        - 'playerBadge.read'