VideoGamesRecords\CoreBundle\Entity\PlayerChartStatus:
  attributes:
    idStatus:
      groups:
        - 'playerChartStatus_show'
    libStatus:
      groups:
        - 'playerChartStatus_show'
    boolRanking:
    boolSendProof:
