VideoGamesRecords\CoreBundle\Entity\Player:
  attributes:
    id:
      groups:
        - 'player.read'
        - 'player.read.mini'
        - 'user.profile'
        - 'player.put'
    pseudo:
      groups:
        - 'player.read'
        - 'player.read.mini'
    presentation:
      groups:
        - 'player.read'
        - 'player.put'
    collection:
      groups:
        - 'player.read'
        - 'player.put'
    slug:
      groups:
        - 'player.read'
        - 'player.read.mini'
    user:
      groups:
        - 'player.user'
    avatar:
      groups:
        - 'player.read'
        - 'player.read.mini'
    country:
      groups:
        - 'player.country'
        - 'player.put'
    rankPointChart:
      groups:
        - 'player.pointChart'
    nbChart:
      groups:
        - 'player.pointChart'
        - 'player.proof'
    nbChartProven:
      groups:
        - 'player.pointChart'
        - 'player.proof'
    nbChartDisabled:
      groups:
        - 'player.pointChart'
        - 'player.proof'
    pointChart:
      groups:
        - 'player.pointChart'
    rankPointGame:
      groups:
        - 'player.pointGame'
    pointGame:
      groups:
        - 'player.pointGame'
    nbGame:
      groups:
        - 'player.pointGame'
    rankMedal:
      groups:
        - 'player.medal'
    chartRank0:
      groups:
        - 'player.medal'
    chartRank1:
      groups:
        - 'player.medal'
    chartRank2:
      groups:
        - 'player.medal'
    chartRank3:
      groups:
        - 'player.medal'
    rankCup:
      groups:
        - 'player.cup'
    gameRank0:
      groups:
        - 'player.cup'
    gameRank1:
      groups:
        - 'player.cup'
    gameRank2:
      groups:
        - 'player.cup'
    gameRank3:
      groups:
        - 'player.cup'
    rankProof:
      groups:
        - 'player.proof'
    rankBadge:
      groups:
        - 'player.badge'
    pointBadge:
      groups:
        - 'player.badge'
    nbMasterBadge:
      groups:
        - 'player.badge'
    team:
      groups:
        - 'user.profile'
        - 'player.team'
        - 'player.put'
        - 'player.profile'
