VideoGamesRecords\CoreBundle\Entity\PlayerChartStatus:
  attributes:
    idStatus:
      groups:
        - 'playerChartStatus.show'
    libStatus:
      groups:
        - 'playerChartStatus.show'
    boolRanking:
    boolSendProof:
