VideoGamesRecords\CoreBundle\Entity\Serie:
  attributes:
    id:
      groups:
        - 'game.show'
        - 'game.list'
    name:
      groups:
        - 'game.show'
        - 'game.list'
    slug:
      groups:
        - 'game.show'
        - 'game.list'
