VideoGamesRecords\CoreBundle\Entity\TeamRequest:
  attributes:
    id:
      groups:
        - 'teamRequest.read'
        - 'teamRequest.put'
    team:
      groups:
        - 'teamRequest.read'
        - 'teamRequest.post'
    player:
      groups:
        - 'teamRequest.read'
        - 'teamRequest.post'
    status:
      groups:
        - 'teamRequest.read'
        - 'teamRequest.put'
    createdAt:
      groups:
        - 'teamRequest.read'

