VideoGamesRecords\CoreBundle\Entity\TeamGame:
  attributes:
    game:
      groups:
        - 'teamGame.game'
    team:
      groups:
        - 'teamGame.team'
    pointChart:
      groups:
        - 'teamGame.pointChart'
    rankPointChart:
      groups:
        - 'teamGame.pointChart'
    pointGame:
      groups:
        - 'teamGame.pointChart'
    rankMedal:
      groups:
        - 'teamGame.medal'
    chartRank0:
      groups:
        - 'teamGame.medal'
    chartRank1:
      groups:
        - 'teamGame.medal'
    chartRank2:
      groups:
        - 'teamGame.medal'
    chartRank3:
      groups:
        - 'teamGame.medal'