VideoGamesRecords\CoreBundle\Entity\TeamBadge:
  attributes:
    badge:
      groups:
        - 'teamBadge.badge'
    createdAt:
      groups:
        - 'teamBadge.read'
    endedAt:
      groups:
        - 'teamBadge.read'