VideoGamesRecords\CoreBundle\Entity\Video:
  attributes:
    id:
      groups:
        - 'video.read'
    libVideo:
      groups:
        - 'video.read'
        - 'video.post'
        - 'video.put'
    slug:
      groups:
        - 'video.read'
    status:
      groups:
        - 'video.read'
    type:
      groups:
        - 'video.read'
    videoId:
      groups:
        - 'video.read'
    url:
      groups:
        - 'video.post'
    tag:
      groups:
        - 'video.post'
        - 'video.put'
    game:
      groups:
        - 'video.read'
        - 'video.post'
    player:
      groups:
        - 'video.read'
        - 'video.post'
    createdAt:
      groups:
        - 'video.read'