VideoGamesRecords\CoreBundle\Entity\VideoComment:
  attributes:
    id:
      groups:
        - 'video.comment.read'
    video:
      groups:
        - 'video.comment.post'
    player:
      groups:
        - 'video.comment.player'
    text:
      groups:
        - 'video.comment.read'
        - 'video.comment.post'
    createdAt:
      groups:
        - 'video.comment.read'
    updatedAt:
      groups: []
