VideoGamesRecords\CoreBundle\Entity\ChartLib:
  attributes:
    idLibChart:
      groups:
        - 'chartLib.read'
    name:
      groups:
        - 'chartLib.read'
    chart:
      groups: []
    type:
      groups:
        - 'chartLib.read'
