VideoGamesRecords\CoreBundle\Entity\PlayerChartStatus:
  attributes:
    id:
      groups:
        - 'playerChartStatus.read'
    class:
      groups:
        - 'playerChartStatus.read'
    name:
      groups:
        - 'playerChartStatus.read'
    boolRanking:
    boolSendProof:
