VideoGamesRecords\CoreBundle\Entity\PlayerBadge:
  attributes:
    id:
      groups:
        - 'playerBadge.read'
        - 'playerBadge.put'
    badge:
      groups:
        - 'playerBadge.badge'
    player:
      groups:
        - 'playerBadge.player'
    mbOrder:
      groups:
        - 'playerBadge.read'
        - 'playerBadge.put'
    title:
      groups:
        - 'playerBadge.read'
    createdAt:
      groups:
        - 'playerBadge.read'
    endedAt:
      groups:
        - 'playerBadge.read'