VideoGamesRecords\CoreBundle\Entity\PlayerPlatform:
  attributes:
    player:
      groups:
        - 'playerPlatform.player'
    platform:
      groups:
        - 'playerPlatform.platform'
    rankPointPlatform:
      groups:
        - 'playerPlatform.pointPlatform'
    pointPlatform:
      groups:
        - 'playerPlatform.pointPlatform'
    nbChart:
      groups:
        - 'playerPlatform.pointPlatform'

