VideoGamesRecords\CoreBundle\Entity\Serie:
  attributes:
    id:
      groups:
        - 'serie.list'
        - 'serie.read'
    name:
      groups:
        - 'serie.list'
        - 'serie.read'
    slug:
      groups:
        - 'serie.list'
        - 'serie.read'
    status:
      groups:
        - 'serie.list'
        - 'serie.read'
    status.value:
      groups:
        - 'serie.list'
        - 'serie.read'
    games:
      groups:
        - 'serie.games'
