VideoGamesRecords\CoreBundle\Entity\TeamGroup:
  attributes:
    group:
      groups: []
    team:
      groups:
        - 'teamGroup.team'
    pointChart:
      groups:
        - 'teamGroup.pointChart'
    rankPointChart:
      groups:
        - 'teamGroup.pointChart'
    pointGame:
      groups: []
    rankMedal:
      groups:
        - 'teamGroup.medal'
    chartRank0:
      groups:
        - 'teamGroup.medal'
    chartRank1:
      groups:
        - 'teamGroup.medal'
    chartRank2:
      groups:
        - 'teamGroup.medal'
    chartRank3:
      groups:
        - 'teamGroup.medal'