VideoGamesRecords\CoreBundle\Entity\Video:
  attributes:
    id:
      groups:
        - 'video.read'
    libVideo:
      groups:
        - 'video.read'
        - 'video.post'
        - 'video.put'
    slug:
      groups:
        - 'video.read'
    status:
      groups:
        - 'video.read'
    type:
      groups:
        - 'video.read'
    videoId:
      groups:
        - 'video.read'
    url:
      groups:
        - 'video.read'
        - 'video.post'
    tag:
      groups:
        - 'video.post'
        - 'video.put'
    title:
      groups:
        - 'video.read'
    description:
      groups:
        - 'video.read'
    viewCount:
      groups:
        - 'video.read'
    likeCount:
      groups:
        - 'video.read'
    thumbnail:
      groups:
        - 'video.read'
    nbComment:
      groups:
        - 'video.read'
    game:
      groups:
        - 'video.game'
        - 'video.post'
    player:
      groups:
        - 'video.player'
    createdAt:
      groups:
        - 'video.read'