resources:
    VideoGamesRecords\CoreBundle\Entity\LostPosition:
        collectionOperations:
            get:
                normalization_context: {'groups': [lostPosition.read, chart.read.mini, chart.group, group.read.mini, group.game, game.read.mini]}
        itemOperations:
            get:
                normalization_context: {'groups': [lostPosition.read]}
            delete:
                access_control: 'is_granted("ROLE_PLAYER") and object.getPlayer().getUser() == user'
                denormalization_context: {'groups': [lostPosition.delete]}