resources:
    VideoGamesRecords\CoreBundle\Entity\Platform:
        attributes:
            pagination_enabled: false
        collectionOperations:
            get:
                normalization_context: {'groups': [platform.read]}
            autocomplete:
                method: 'GET'
                normalization_context: { 'groups': [ platform.read ] }
                path: '/platforms/autocomplete'
                swagger_context:
                    parameters:
                        -   name: query
                            in: query
                            required: true
                            type: string
                controller: 'VideoGamesRecords\CoreBundle\Controller\PlatformController::autocomplete'
        itemOperations:
            get:
                normalization_context: {'groups': [platform.read]}
            player-ranking-point:
                method: 'GET'
                normalization_context: { 'groups': [ playerPlatform.pointPlatform,playerPlatform.player,player.read.mini,player.team,team.read.mini,player.country,country.read ] }
                path: '/platforms/{id}/player-ranking-point'
                swagger_context:
                    parameters:
                        -   name: id
                            in: path
                            required: true
                            type: integer
                        -   name: maxRank
                            in: query
                            required: false
                            type: integer
                controller: 'VideoGamesRecords\CoreBundle\Controller\Ranking\PlatformController::getRankingPoints'