resources:
    VideoGamesRecords\CoreBundle\Entity\Proof:
        collectionOperations:
            get: ~
        itemOperations:
            get:
                normalization_context: {'groups': [proof.read, picture.read]}
            put:
                access_control: 'is_granted("ROLE_USER") and object.getPlayer().getUserId() == user.getId()'
                denormalization_context: { 'groups': [ proof.put ] }
                normalization_context: { 'groups': [ proof.read, picture.read ] }